addSbtPlugin("org.scalameta"    % "sbt-scalafmt"        % "2.5.2")
addSbtPlugin("org.scoverage"    % "sbt-coveralls"       % "1.3.2")
addSbtPlugin("org.scoverage"    % "sbt-scoverage"       % "1.9.3")
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.8.1")
addSbtPlugin("com.geirsson"     % "sbt-ci-release"      % "1.5.7")
