addSbtPlugin("org.scalameta"  % "sbt-scalafmt"        % "2.5.2")
addSbtPlugin("org.scoverage"  % "sbt-coveralls"       % "1.3.11")
addSbtPlugin("org.scoverage"  % "sbt-scoverage"       % "2.0.12")
addSbtPlugin("com.github.sbt" % "sbt-native-packager" % "1.10.0")
addSbtPlugin("com.github.sbt" % "sbt-ci-release"      % "1.9.0")
